---

# 1. Check for required facts
# -----------------------------------------------------------------------------
- name: "Fail if bas_endpoint_url has not been provided"
  when: bas_endpoint_url is not defined or bas_endpoint_url|length == 0
  fail:
    msg: "bas_endpoint_url property has not been set"

- name: "Fail if bas_api_key has not been provided"
  when: bas_api_key is not defined or bas_api_key|length == 0
  fail:
    msg: "bas_api_key property has not been set"

# - name: "Fail if bas_segment_key has not been provided"
#   when: bas_segment_key is not defined or bas_segment_key|length == 0
#   fail:
#     msg: "bas_segment_key property has not been set"

- name: "Fail if bas_tls_crt has not been provided"
  when: bas_tls_crt is not defined or bas_tls_crt|length == 0
  fail:
    msg: "bas_tls_crt property has not been set"

# 2. Provide Debug information
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "BAS URL ...................... {{ bas_endpoint_url }}"

# 3. MAS Config
# -----------------------------------------------------------------------------
- include_tasks: tasks/bascfg.yml
  when: mas_instance_id is defined
