---

# Ansible can't support block retries, this is a relatively simple workaround
# to achieve the same thing
# https://github.com/ansible/ansible/issues/46203#issuecomment-556013701

- name: 'wait : Wait until all services are ready'
  block:
    - name: "wait : Set the retry count"
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count|int + 1 }}"
        services_count: 0
        ready_services_count: 0

    - name: "wait : Lookup CPD Service Subscriptions operators"
      vars:
        service_name: "{{ item }}"
      community.kubernetes.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ hostvars[inventory_hostname][item].operatorname }}"
        namespace: "{{ cpd_meta_namespace }}"
      register: cpd_services_lookup
      with_items: "{{ cpd_services }}"

    - name: "wait : Check if CPD Service Subscriptions operators are running"
      set_fact:
        services_count: "{{ services_count|int + 1 }}"
        ready_services_count: "{{ ready_services_count|int + 1 if (item.resources[0].status.availableReplicas is defined and item.resources[0].status.availableReplicas == 1) else ready_services_count|int}}"
      with_items: "{{ cpd_services_lookup.results }}"
      loop_control:
        label: "{{ item.resources[0].metadata.name if (item.resources[0] is defined and item.resources[0] | length > 0) else 'Subscription is being installed;' }} operator available replicas = {{ item.resources[0].status.availableReplicas if (item.resources[0] is defined and item.resources[0].status.availableReplicas is defined) else 0}}"

    - name: "wait : Fail if one or more CPD Service Subscriptions operators are not running"
      when: ready_services_count != services_count
      fail:
        msg: "[{{ retry_count }}/30] {{ ready_services_count }} of {{ services_count }} services are ready"
  rescue:
    - name: "wait : Give up after 30 attempts (approx 30 minutes)"
      when: retry_count|int >= 30
      fail:
        msg: Timed out waiting for service operator to be ready

    - name: "wait : Wait for 60 seconds before checking again"
      pause:
        seconds: 60

    - include_tasks: wait_for_subscriptions.yml
