kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dbwh-tls-route
  namespace: "{{db2wh_namespace}}"
spec:
  host: >-
    {{db2wh_instance_name | lower }}-{{db2wh_namespace}}.{{_cluster_subdomain.resources[0].spec.domain}}
  to:
    kind: Service
    name: "c-{{db2wh_instance_name | lower}}-db2u-engn-svc"
    weight: 100
  port:
    targetPort: ssl-server
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
