galaxy_info:
  author: Alexandre Quinteiro (@alequint)
  description: Deploy IBM DB2 instance configured for IBM Maximo Application Suite (using CP4D APIs)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - db2

dependencies:
  - role: ibm.mas_devops.ansible_version_check
