---

# 1. Check for missing properties that do not have defaults
# -----------------------------------------------------------------------------
- name: "Fail if sls_url has not been provided"
  when: sls_url is not defined or sls_url|length == 0
  fail:
    msg: "sls_url property has not been set"

- name: "Fail if sls_registration_key has not been provided"
  when: sls_registration_key is not defined or sls_registration_key|length == 0
  fail:
    msg: "sls_registration_key property has not been set"

- name: "Fail if sls_tls_crt has not been provided"
  when: sls_tls_crt is not defined or sls_tls_crt|length == 0
  fail:
    msg: "sls_tls_crt property has not been set"

# 2. Generate SLSCfg for MAS
# -----------------------------------------------------------------------------
- include_tasks: tasks/slscfg.yml
  # when:
  #   - mas_instance_id is defined
  #   - mas_instance_id|length > 0
  #   - mas_config_dir is defined
  #   - mas_config_dir|length > 0

