---
# 1. Write out the config to the local filesystem
# -----------------------------------------------------------------------------
- name: Copy SLSCfg to filesytem
  ansible.builtin.template:
    src: slscfg.yml.j2
    dest: "{{ mas_config_dir }}/sls.yml"
    mode: '644'
