---

# 1. Generate the configuration
# -----------------------------------------------------------------------------

- name: Obtain BAS Certificate
  k8s_info:
    api_version: v1
    kind: Route
    name: bas-endpoint
    namespace: "{{ bas_namespace }}"
  register: bas_endpoint


- name: Lookup bas-api-key
  k8s_info:
    api_version: v1
    kind: Secret
    name: bas-api-key
    namespace: "{{ bas_namespace }}"
  register: bas_apikey_result

# - name: Lookup BAS segment key
#   k8s_info:
#     api_version: v1
#     kind: Secret
#     name: segment-key-secret
#     namespace: "{{ bas_namespace }}"
#   register: bas_segment_key_result


- name: Lookup Certificate for BAS
  k8s_info:
    api_version: v1
    kind: Secret
    name: router-ca
    namespace: openshift-ingress-operator
  register: bas_certificates_result

- name: Set facts for BASCfg
  set_fact:
    # bas_segment_key: "{{bas_segment_key_result.resources[0].data.segmentkey | b64decode}}"
    bas_api_key: "{{bas_apikey_result.resources[0].data.apikey | b64decode }}"
    bas_endpoint_url: "https://{{bas_endpoint.resources[0].spec.host}}"
    bas_tls_crt: "{{bas_certificates_result.resources[0].data['tls.crt'] | b64decode }}"


# 2. Write out the config to the local filesystem
# -----------------------------------------------------------------------------
- name: Copy BASCfg to filesytem
  ansible.builtin.template:
    src: bascfg.yml.j2
    dest: "{{ mas_config_dir }}/bas-{{ bas_namespace }}.yml"
    mode: '644'

