---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cp4d-ca-crt
  namespace: "{{cpd_meta_namespace}}"
spec:
  isCA: true
  secretName: cp4d-ca-secret
  commonName: "public.{{ cpd_meta_namespace }}.cp4d.ibm.com"
  duration: 17520h # 2years
  privateKey:
    algorithm: ECDSA
    size: 256
  
  dnsNames:
  - "*.apps.{{cluster_name}}.{{base_domain}}"
  - "*.svc.cluster.local"
  - "api-svc"
  - "ibm-nginx-svc"
  - "zen-core-api"

  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io