apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c4pd
  namespace: "{{cpd_meta_namespace}}"
spec:
  duration: 17520h # 2years
  dnsNames:
  - "*.apps.{{cluster_name}}.{{base_domain}}"  
  - "*.svc.cluster.local"
  - "api-svc"
  - "ibm-nginx-svc"
  - "zen-core-api"

  issuerRef:
    name: cp4d-issuer
  secretName: external-tls-secret-temp