---
# cpd_services_namespace: 'cpd-services'
# cpd_meta_namespace: 'ibm-common-services'

db2wh:
  apiVersion: databases.cpd.ibm.com/v1
  operatorname: ibm-db2wh-cp4d-operator-controller-manager
  crdkind: Db2whService
  crname: cloudpak-db2whservice
dods:
  apiVersion: dods.cpd.ibm.com/v1beta1
  operatorname: ibm-cpd-dods-operator
  crdkind: DODS
  crname: dods-cr
wml:
  apiVersion: wml.cpd.ibm.com/v1beta1
  operatorname: ibm-cpd-wml-operator
  crdkind: WmlBase
  crname: wml-cr
spark:
  apiVersion: ae.cpd.ibm.com/v1
  operatorname: ibm-cpd-ae-operator
  crdkind: AnalyticsEngine
  crname: analyticsengine-sample
wsl:
  apiVersion: ws.cpd.ibm.com/v1beta1
  operatorname: ibm-cpd-ws-operator
  crdkind: WS
  crname: ws-cr
aiopenscale:
  apiVersion: wos.cpd.ibm.com/v1
  operatorname: ibm-cpd-wos-operator
  crdkind: WOService
  crname: aiopenscale
dmc:
  apiVersion: dmc.databases.ibm.com/v1
  operatorname: ibm-dmc-controller-manager
  crdkind: Dmcaddon
  crname: dmc-addon
wd:
  apiVersion: discovery.watson.ibm.com/v1
  operatorname: wd-discovery-operator
  crdkind: WatsonDiscovery
  crname: wd
