---
cpd_version: "{{ lookup('env', 'CPD_VERSION') }}"
# As an alternative to using the cpd_version, the mas_channel can be used to dynamically determine the correct
# version of CPD to install (in some cases, but not all)
mas_channel: "{{ lookup('env', 'MAS_CHANNEL') }}"

cpd_registry: cp.icr.io
cpd_registry_user: cp

# This is only used for cpd35, we have to use cp4d_hack_worker_nodes to set up the global image pull secret needed by cpd40
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"

# both storage classes for cpd should be ibmc-file-gold-gid as per recommendation from cpd support team
# so we're deliberately forcing both 'cpd_storage_class' and 'cpd_metadb_storage_class' to be the same for now
# but still making 'cpd_metadb_storage_class' available as this well might change in the future
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-storage
cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"
# cpd_metadb_storage_class: "{{ lookup('env', 'CPD_METADB_STORAGE_CLASS') }}"
cpd_metadb_storage_class: "{{ cpd_storage_class }}"

# --- MAS channel control ---------------------------------------------------------------------------------------------
# Temporary solution: this will be used to determine whether to install CPD v4 or v3.5, if MAS channels from the below
# list are selected (older MAS releases still supporting CPD V3.5), then CPD v3.5 will be installed, otherwise CPD v4.0
# By default will we assume that we are installing for the main 8.x channel
mas_channels_old_releases: ['8.6.x', '8.5.x']
cpd_supported_versions: ['cpd35', 'cpd40']
