---
- name: "Fail if db2wh_instance_name has not been provided"
  when: db2wh_instance_name is not defined or db2wh_instance_name == ""
  fail:
    msg: "db2wh_instance_name property has not been set"

# 1. Determine which version of CP4D we are working with
# -----------------------------------------------------------------------------
# - if cpd_version is set explicitly then we use that
# - if cpd-meta-ops namespace exists then we assume it's 3.5
# - otherwise we assume CPD v4

- name: Check for the presence of the CPDv4 services namespace
  when: cpd_version is not defined or cpd_version == ''
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Namespace
    name: cpd-meta-ops
  register: cpd3_namespace_lookup

- name: Set cpd_version to cpd35 if we found the CP4D v3 namespace
  when:
    - cpd_version is not defined or cpd_version == ''
    - cpd3_namespace_lookup.resources is defined
    - cpd3_namespace_lookup.resources | length == 1
  set_fact:
    cpd_version: cpd35

- name: Default to cpd40 if we did not find the CP4D v3 namespace
  when: cpd_version is not defined or cpd_version == ''
  set_fact:
    cpd_version: cpd40


# 2. Set db2wh_version if none provided by the user
# -----------------------------------------------------------------------------
- name: Set db2wh_version if none provided by the user
  when: db2wh_version is not defined or db2wh_version == ''
  set_fact:
    db2wh_version: "{{ default_db2wh_version[cpd_version] }}"

- debug:
    msg:
      - "CPD Version ........................... {{ cpd_version }}"
      - "DB2WH Version ......................... {{ db2wh_version }}"

# 3. Taint and label dedicated node if specified
# -----------------------------------------------------------------------------
- name: Taint and label dedicated worker node
  when:
    - db2wh_node_label is defined and db2wh_node_label != ''
    - db2wh_dedicated_node is defined and db2wh_dedicated_node != ''
  shell: |
    oc adm taint node {{ db2wh_dedicated_node }} icp4data={{ db2wh_node_label }}:NoSchedule --overwrite
    oc adm drain {{ db2wh_dedicated_node }} --ignore-daemonsets --delete-local-data
    oc label node {{ db2wh_dedicated_node }} icp4data={{ db2wh_node_label }} --overwrite
    oc adm uncordon {{ db2wh_dedicated_node }}

# 4. Load var files
# -----------------------------------------------------------------------------
## not loading for now, reading from env
# - name: Load variables
#   include_vars: "vars/{{ cpd_version }}.yml"

- name: Provision DB2 instance
  include_tasks: "tasks/{{ cpd_version }}/provision-instance.yml"
