---
# The following playbook is an attempt to automate the CP4D 4.0 steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html

# 1. Fail if no required keys are provided
# -----------------------------------------------------------------------------
- name: "Fail if cpd_storage_class has not been provided"
  when: cpd_storage_class is not defined or cpd_storage_class == ""
  fail:
    msg: "cpd_storage_class property has not been set"

- name: "Fail if cpd_metadb_storage_class has not been provided"
  when: cpd_metadb_storage_class is not defined or cpd_metadb_storage_class == ""
  fail:
    msg: "cpd_metadb_storage_class property has not been set"

- name: "Debug information"
  debug:
    msg:
      - "CPD meta namespace ........... {{ cpd_meta_namespace }}"
      - "CPD services namespace ....... {{ cpd_services_namespace }}"
      - "CPD registry ................. {{ cpd_registry }}"
      - "CPD username ................. {{ cpd_registry_user }}"
      - "CPD storage class ............ {{ cpd_storage_class }}"
      - "CPD metadb storage class ...... {{ cpd_metadb_storage_class }}"

# 2. Setup namespace for CP4D
# -----------------------------------------------------------------------------
- name: "Check if ibm-common-services operator is installed already"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: ibm-common-service-operator
    namespace: ibm-common-services
    kind: Deployment
  register: _cs_deployment

- name: "Create CPD 4.0 Namespace"
  vars:
    namespace: "{{ cpd_meta_namespace }}"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpd40/namespace.yaml') }}"
  register: _cpd_meta_namespace_result


# 3. Install CP4D operator
# -----------------------------------------------------------------------------
- name: "Apply operator group"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpd40/operatorgroup.yaml') }}"
  when: _cs_deployment.resources[0] is not defined

- name: "Install CPD 4.0 Subscription"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpd40/subscription-cpd-operator.yaml') }}"
  register: _cpd_subscription_result

- name: "Wait for cpd-platform-operator-manager to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: cpd-platform-operator-manager
    namespace: "{{ cpd_meta_namespace }}"
    kind: Deployment
  register: _cpd_subscription
  until: _cpd_subscription.resources[0].status.availableReplicas is defined
  retries: 10 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute

- name: "Wait for operand-deployment-lifecycle-manager to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: operand-deployment-lifecycle-manager
    namespace: "{{ cpd_meta_namespace }}"
    kind: Deployment
  register: _operand_subscription
  until: _operand_subscription.resources[0].status.availableReplicas is defined
  retries: 10 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute


# 4. Install CP4D
# -----------------------------------------------------------------------------
- name: "Apply CloudPak for Data 4.0 - Operand Request"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpd40/operand.yaml') }}"
  register: _cpd_operand_result

- name: "Again wait for cpd-platform-operator-manager to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: cpd-platform-operator-manager
    namespace: "{{ cpd_meta_namespace }}"
    kind: Deployment
  register: _cpd_subscription
  until: _cpd_subscription.resources[0].status.availableReplicas is defined
  retries: 10 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute

- name: "Apply CloudPak for Data 4.0 CR"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cpd40/ibmcpd.yaml') }}"
  register: _cpd_ibmcdp_result

- name: "Wait for ibm-zen-operator to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: ibm-zen-operator
    namespace: "{{ cpd_meta_namespace }}"
    kind: Deployment
  register: _zen_deployment
  until: _zen_deployment.resources[0].status.availableReplicas is defined
  retries: 90 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute

- name: "Wait for ibmcpd CPD 4.0 to be Completed"
  community.kubernetes.k8s_info:
    api_version: cpd.ibm.com/v1
    name: ibmcpd-cr
    namespace: "{{ cpd_services_namespace }}"
    kind: Ibmcpd
  register: _ibmcpd_subscription
  until: _ibmcpd_subscription.resources[0].status.controlPlaneStatus == "Completed"
  retries: 90 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute

- name: "Wait for ZenService CPD 4.0 to be Completed"
  community.kubernetes.k8s_info:
    api_version: zen.cpd.ibm.com/v1
    name: lite-cr
    namespace: "{{ cpd_services_namespace }}"
    kind: ZenService
  register: _zen_subscription
  until: _zen_subscription.resources[0].status.zenStatus == "Completed"
  retries: 90 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute

# 5. Provide CP4D dashboard URL
# -----------------------------------------------------------------------------
- name: "Retrieve admin credentials"
  community.kubernetes.k8s_info:
    api_version: v1
    name: admin-user-details
    namespace: "{{ cpd_services_namespace }}"
    kind: Secret
  register: _cpd_admin

- name: "Obtain CP4D dashboard URL"
  debug:
    msg:
      - "CP4D Dashboard ................. https://{{_zen_subscription.resources[0].status.url}}"
      - "CP4D Username .................. admin"
      - "CP4D Password .................. Found in 'admin-user-details' secret under '{{ cpd_services_namespace }}' namespace"
