---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "jdbc-{{ db2wh_instance_name | lower }}-credentials"
  namespace: "mas-{{mas_instance_id}}-core"
stringData:
  username: "{{ db2wh_jdbc_username }}"
  password: "{{ db2wh_jdbc_password }}"
---
apiVersion: config.mas.ibm.com/v1
kind: JdbcCfg
metadata:
  name: "{{ suite_jdbccfg_name }}"
  namespace: "mas-{{ mas_instance_id }}-core"
  labels: {{ suite_jdbccfg_labels }}
spec:
  displayName: "{{ db2wh_instance_name | lower }} on CP4D"
  config:
    url: "{{ db2wh_jdbc_url }}"
    sslEnabled: true
    credentials:
      secretName: "jdbc-{{ db2wh_instance_name | lower }}-credentials"
  certificates:
    - alias: "{{ db2wh_instance_name | lower }}"
      crt: |
        {{ db2wh_certificate | indent(8) }}
