---
apiVersion: ae.cpd.ibm.com/v1
kind: AnalyticsEngine
metadata:
  name: analyticsengine-sample     # This is the recommended name, but you can change it
  namespace: "{{ cpd_services_namespace }}"    # Replace with the project where you will install Analytics Engine Powered by Apache Spark
spec:
  license:
    accept: true
    license: Standard     # Specify the license you purchased
  version: 4.0.3
  storageClass: "{{ cpd_storage_class }}"
