---
apiVersion: wml.cpd.ibm.com/v1beta1
kind: WmlBase
metadata:
  name: wml-cr
  namespace: "{{ cpd_services_namespace }}"
spec:
  ignoreForMaintenance: false
  license:
    accept: true
    license: Standard
  storageClass: "{{ cpd_storage_class }}"
  version: 4.0.3
  scaleConfig: small
