---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # MAS instance configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
    sls_tls_crt: "{{ lookup('file', '~/mas-multicloud/sls.crt') }}"
    sls_url: "{{ lookup('env', 'SLS_ENDPOINT_URL') }}"
    sls_registration_key: "{{ lookup('env', 'SLS_REGISTRATION_KEY') }}"
    # Destination for the generated MAS SlsCfg resource template
    sls_cfg_file: "{{ mas_config_dir }}/sls.yml"

  roles:
    - sls_cfg
