---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # MAS Configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

    # BAS Configuration
    bas_tls_crt: "{{ lookup('file', '~/mas-on-aws/bas.crt') }}"
    bas_endpoint_url: "{{ lookup('env', 'BAS_ENDPOINT_URL') }}"
    bas_api_key: "{{ lookup('env', 'BAS_API_KEY') }}"
    # bas_segment_key: "{{ lookup('env', 'BAS_SEGMENT_KEY') }}"
    # Destination for the generated MAS SlsCfg resource template
    bas_cfg_file: "{{ mas_config_dir }}/bas.yml"
    contact:
      email: "{{ lookup('env', 'BAS_CONTACT_MAIL') | default('john@mycompany.com', true) }}"
      firstName: "{{ lookup('env', 'BAS_CONTACT_FIRSTNAME') | default('John', true) }}"
      lastName: "{{ lookup('env', 'BAS_CONTACT_LASTNAME') | default('Barnes', true) }}"

  roles:
  - bas_cfg
