apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: ws-cr
  namespace: "{{ cpd_services_namespace }}"
spec:
  ignoreForMaintenance: false
  license:
    accept: true
    license: Standard
  scaleConfig: small
  storageClass: "{{ cpd_storage_class }}"
  version: 4.0.3
