---
# -----------------------------------------------------------------------------
# Set CP4D Bearer Token (cp4d_bearer_token) into Facts
# -----------------------------------------------------------------------------
- name: Authorize the CP4D (get Bearer token)
  uri:
    url: "https://{{ cp4d_host }}/icp4d-api/v1/authorize"
    validate_certs: no
    method: POST
    headers:
      cache-control: "no-cache"
    body_format: "json"
    body: "{\"username\":\"{{ cpd_api_username }}\",\"password\":\"{{ cpd_api_password }}\"}"
    status_code: 200
    timeout: 30
  register: cp4d_authorization

- name: Get the CP4D Bearer token
  set_fact:
    cp4d_bearer_token: "{{ cp4d_authorization.json.token }}"
