---
- name: Check if cert-manager is installed
  community.kubernetes.k8s_info:
    api_version: v1
    name: cert-manager
    namespace: "cert-manager"
    kind: Deployment
  register: _cert_manager_deployed

# if cert-manager from cert-manager namespace is deployed, then it will be used per default otherwise set ibm-cert-manager from ibm-common-services to be used
- name: Define which cert-manager to use
  when: _cert_manager_deployed.resources is defined and _cert_manager_deployed.resources | length == 0
  set_fact:
    certManager:
      namespace: ibm-common-services
      serviceAccountName: ibm-cert-manager-controller

- debug:
    msg:
      - "Cert-manager namespace: {{ certManager.namespace }}"
      - "Cert-manager service account: {{ certManager.serviceAccountName }}"

- include_tasks: tasks/providers/cis/main.yml
  when:
    - custom_domain != ""
    - custom_cluster_issuer != ""
    - cis_crn is defined
    - cis_email is defined
    - ibmcloud_apikey is defined
