---
- include_tasks: tasks/providers/cis/main.yml
  when:
    - custom_domain|length > 0
    - custom_cluster_issuer|length > 0
    - cis_crn is defined
    - cis_email is defined
    - ibmcloud_apikey is defined
