---
# Note: This version of cert-manager is only intended for use with MAS v8.6 or earlier

- name: Install Cert Manager (Standalone)
  shell: |
    oc create namespace cert-manager
    oc apply -f https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml
