---
# 1.  Install Service Binding Operator (stable channel)
# -----------------------------------------------------------------------------
- name: "sbo/stable : Create SBO Subscription"
  community.kubernetes.k8s:
    template: templates/sbo/subscription-stable.yml
    wait: yes
    wait_timeout: 120

- name: "sbo/stable : Lookup SBO install plan"
  community.kubernetes.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: openshift-operators
    label_selectors:
      - operators.coreos.com/rh-service-binding-operator.openshift-operators
  register: sbo_installplan_info
  retries: 20
  delay: 60 # Retry for approx 20 minutes (60s * 20 attempts) before giving up
  until: sbo_installplan_info.resources | length > 0

- name: "sbo/stable : Wait for SBO install to complete"
  when:
    - sbo_installplan_info.resources[0].status.phase != "Complete"
  community.kubernetes.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ sbo_installplan_info.resources[0].metadata.name }}"
    namespace: openshift-operators
  register: sbo_installplan_info
  retries: 20
  delay: 30 # Retry for approx 10 minutes (20s * 30 attempts) before giving up
  until:
    - sbo_installplan_info.resources[0].status.phase is defined
    - sbo_installplan_info.resources[0].status.phase == "Complete"
