suite_jdbccfg_name: "{{ mas_instance_id }}-jdbc-ws-{{mas_workspace_id}}"
suite_jdbccfg_labels:
  mas.ibm.com/configScope: workspace-application
  mas.ibm.com/instanceId: "{{ mas_instance_id }}"
  mas.ibm.com/workspaceId: "{{ mas_workspace_id }}"
