apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: behavior-analytics-services-operator-certified
  namespace: "{{bas_namespace}}"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: behavior-analytics-services-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
