# Lookup the server certificate
- name: "Lookup the external-tls-secret-temp"
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: external-tls-secret-temp
    namespace: "{{ cpd_meta_namespace }}"
  register: external_tls_secret

- name: "Create external-tls-secret"
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "external-tls-secret"
        namespace: "{{ cpd_meta_namespace }}"
      data:
        cert.crt: "{{ external_tls_secret.resources[0].data['tls.crt'] }}"
        cert.key: "{{ external_tls_secret.resources[0].data['tls.key']  }}" 