---
mas_app_ws_fqn: manageworkspaces.apps.mas.ibm.com
mas_app_ws_kind: ManageWorkspace
mas_app_ws_spec:
  bindings:
    jdbc: "workspace-application"
    # jdbc: system
  components:
    base:
      version: latest
  settings:
    db:
      dbSchema: maximo
      maxinst:
        demodata: "{{ manage_demo_data | bool }}"
        db2Vargraphic: true
        indexSpace: MAXINDEX
        tableSpace: MAXDATA
        bypassUpgradeVersionCheck: false
